---

- debug:
    msg: "******************** SENAITE PLONE [START] ********************"

- name: "Run SENAITE PLONE"
  include_role:
    name: plone.plone_server
  vars:
    plone_config: "{{ senaite_plone_config[0] }}"

- name: "Run buildout - output goes to {{ plone_instance_home }}/buildout.log"
  shell: "bin/buildout -c live.cfg > buildout.log 2>&1"
  args:
    chdir: "{{ plone_instance_home }}"
  become_user: "{{ plone_buildout_user }}"
  notify: restart supervisor
  tags:
    - senaite-plone

- name: Fix permission issues with buildout-cache eggs
  shell: "chmod -R ug+rwX,o-rwx {{ plone_target_path }}/buildout-cache/eggs"
  become: yes
  tags:
    - senaite-plone

- name: "Add site's admin user"
  shell: "bin/client_reserved adduser admin {{ plone_initial_password }}"
  args:
    chdir: "{{ plone_instance_home }}"
  become_user: "{{ plone_daemon_user }}"
  tags:
    - senaite-plone

- name: Insert Supervisor HTTP Server Block
  blockinfile:
    dest: /etc/supervisor/supervisord.conf
    block: |
      [inet_http_server]
      port = {{ supervisor_http_port }}
      username = {{ supervisor_http_user }}
      password = {{ supervisor_http_pass }}
    state: present
  when: supervisor_with_http
  notify: restart supervisor
  tags:
    - senaite-supervisor

- name: Remove Supervisor HTTP Server Block
  blockinfile:
    dest: /etc/supervisor/supervisord.conf
    block: |
      [inet_http_server]
      port = {{ supervisor_http_port }}
      username = {{ supervisor_http_user }}
      password = {{ supervisor_http_pass }}
    state: absent
  when: not supervisor_with_http
  notify: restart supervisor
  tags:
    - senaite-supervisor

- name: Copy Git Config
  template:
    src: gitconfig.j2
    dest: "/home/senaite/.gitconfig"
    owner: senaite
    group: senaite
    mode: 0644
  tags:
    - senaite-git

- name: Copy Git Ignores
  template:
    src: gitignore.j2
    dest: "/home/senaite/.gitignore"
    owner: senaite
    group: senaite
    mode: 0644
  tags:
    - senaite-git

- debug:
    msg: "******************** SENAITE PLONE [DONE] ********************"
